export const PRESET_KEYWORDS = [
  // ==========================================
  // PROJECT ADJECTIVES & BUZZWORDS (1 - 100)
  // ==========================================
  "Smart", "Intelligent", "Autonomous", "Advanced", "Next Generation",
  "Automated", "Sustainable", "Eco Friendly", "Hybrid", "Integrated",
  "Real Time", "Dynamic", "Adaptive", "Optimized", "Distributed",
  "Cloud Based", "Web Based", "Mobile Based", "IoT Enabled", "AI Powered",
  "Machine Learning Driven", "Deep Learning Based", "Blockchain Enabled", "Sensor Based", "Voice Controlled",
  "Gesture Controlled", "Remote Controlled", "Wireless", "Virtual", "Digital",
  "Interactive", "Responsive", "High Performance", "Low Cost", "Affordable",
  "Portable", "Compact", "Modular", "Scalable", "Robust",
  "Secure", "Encrypted", "Decentralized", "Efficient", "Eco Smart",
  "Green", "Clean Energy", "Renewable", "Smart City", "Smart Home",
  "Smart Grid", "Precision", "Cognitive", "Biomimetic", "Pneumatic",
  "Hydraulic", "Serverless", "Microservices Based", "Cross Platform", "Full Stack",
  "Data Driven", "Predictive", "Analytical", "Vision Based", "LiDAR Based",
  "Solar Powered", "Wind Powered", "Electric Vehicle", "Drone Based", "Robotic",
  "Wearable", "Embedded", "Programmable", "Industrial", "Commercial",
  "Agricultural", "Biomedical", "Automotive", "Aerospace", "Marine",
  "Universal", "Multi Purpose", "Configurable", "Self Healing", "Self Driving",
  "Assistive", "Prosthetic", "Augmented", "Virtual Reality Based", "Haptic",
  "Turnkey", "Customized", "Low Power", "High Speed", "Open Source",

  // ==========================================
  // GENERIC COMBINATIONS & GENERAL TERMS (101 - 200)
  // ==========================================
  "AI & ML", "Artificial Intelligence & Machine Learning", "Data Science & Analytics", "IoT & Embedded Systems", "Robotics & Automation",
  "VLSI & Embedded", "Cloud & DevOps", "Cybersecurity & Cryptography", "Web & Mobile Development", "AR & VR",
  "System Architecture", "Prototype Design", "Simulation & Analysis", "Experimental Setup", "Hardware Model",
  "Software System", "Framework Development", "Algorithm Design", "Mathematical Modeling", "Statistical Analysis",
  "Optimization Technique", "Comparative Study", "Feasibility Analysis", "Performance Evaluation", "Case Study",
  "Design & Implementation", "Development & Testing", "Analysis & Simulation", "Modeling & Control", "Monitoring System",
  "Control System", "Automation System", "Management System", "Tracking System", "Detection System",
  "Recognition System", "Classification System", "Prediction System", "Recommendation System", "Information System",
  "Decision Support System", "Security System", "Surveillance System", "Navigation System", "Communication System",
  "Power System", "Energy System", "Structural System", "Transportation System", "Environmental System",
  "Fluid System", "Thermal System", "Manufacturing System", "Production System", "Quality Control System",
  "Data Acquisition", "Signal Processing System", "Image Processing System", "Network Architecture", "Database System",
  "Application Software", "Embedded Application", "Web Application System", "Mobile Application System", "Cloud Service",
  "Smart Device", "Wearable Device", "Sensor Node", "Actuator Network", "Robotic Arm",
  "Mobile Robot", "Autonomous Vehicle", "Unmanned Aerial Vehicle System", "Electric Vehicle System", "Battery Management",
  "Renewable Energy Source", "Solar Panel Array", "Wind Turbine System", "Smart Water System", "Waste Management System",
  "Traffic Management", "Urban Infrastructure", "Green Building System", "Sustainable Design Project", "Industrial Tool",

  // ==========================================
  // COMPUTER SCIENCE & AI (201 - 300)
  // ==========================================
  "Artificial Intelligence", "Machine Learning", "Deep Learning", "Neural Networks", "Natural Language Processing",
  "Computer Vision", "Reinforcement Learning", "Generative AI", "Large Language Models", "Data Science",
  "Data Analytics", "Big Data", "Predictive Modeling", "Data Mining", "Data Visualization",
  "Full Stack Development", "Frontend Architecture", "Backend Engineering", "Web Application", "Mobile App Development",
  "Android Development", "iOS Development", "Cross Platform Apps", "Cloud Computing", "Amazon Web Services (AWS)",
  "Microsoft Azure", "Google Cloud Platform", "Serverless Architecture", "DevOps", "CI/CD Pipelines",
  "Docker Containers", "Kubernetes", "Microservices", "Cybersecurity", "Ethical Hacking",
  "Cryptography", "Network Security", "Penetration Testing", "Blockchain Technology", "Smart Contracts",
  "Decentralized Apps (dApps)", "Web3", "Internet of Things (IoT)", "Edge Computing", "Fog Computing",
  "Embedded Software", "Real Time Operating Systems", "Computer Architecture", "Compiler Design", "Operating Systems",
  "Database Management", "SQL Databases", "NoSQL Databases", "Graph Databases", "Object Oriented Programming",
  "Functional Programming", "Data Structures", "Algorithms Optimization", "Software Architecture", "Design Patterns",
  "Agile Methodologies", "Scrum Framework", "Git Version Control", "Linux Systems", "Shell Scripting",
  "Python Programming", "Java Programming", "C Plus Plus", "JavaScript Ecosystem", "TypeScript",
  "Rust Programming", "Go Language", "Next.js Framework", "React Library", "Angular Framework",
  "Vue.js", "Node.js Backend", "Django Framework", "Flask Microframework", "FastAPI",
  "Spring Boot", "GraphQL API", "RESTful Web Services", "UI UX Design", "Responsive Web Design",
  "Human Computer Interaction", "Virtual Reality (VR)", "Augmented Reality (AR)", "Mixed Reality", "Metaverse Development",
  "Game Development", "Unity 3D Engine", "Unreal Engine", "Computer Graphics", "Digital Audio Processing",
  "Distributed Systems", "Parallel Computing", "High Performance Computing", "Quantum Computing", "Bioinformatics",

  // ==========================================
  // TECHNICAL SUB-DOMAINS & FIELDS (301 - 400)
  // ==========================================
  "Pattern Recognition", "Anomaly Detection", "Sentiment Analysis", "Text Summarization", "Speech Recognition",
  "Object Detection", "Image Segmentation", "Face Recognition", "Gesture Recognition", "Predictive Maintenance",
  "Fraud Detection", "Recommendation Engine", "Chatbot Development", "Virtual Assistant", "Autonomous Navigation",
  "API Development", "Database Optimization", "Network Load Balancing", "Cloud Security", "Identity Access Management",
  "Vulnerability Assessment", "Malware Analysis", "Digital Forensics", "Distributed Ledgers", "NFT Development",
  "MQTT Protocol", "CoAP Protocol", "Wireless Mesh Networks", "Edge Analytics", "Real Time Streaming",
  "Data Warehousing", "ETL Pipelines", "Data Governance", "MLES (Machine Learning at Scale)", "MLOps",
  "Hyperparameter Tuning", "Model Deployment", "Feature Engineering", "Time Series Forecasting", "Cluster Analysis",
  "Semantic Web", "Knowledge Graphs", "Ontology Engineering", "Search Engine Optimization", "Web Scraping",
  "Microfrontend Architecture", "Progressive Web Apps", "Server Side Rendering", "Static Site Generation", "State Management",
  "Unit Testing", "Integration Testing", "Automated Testing", "Performance Testing", "Load Testing",
  "Linux Kernel", "Device Drivers", "Memory Management", "Process Synchronization", "File Systems",
  "Parallel Programming", "CUDA Programming", "OpenCL Development", "MPI (Message Passing Interface)", "Grid Computing",
  "Quantum Algorithms", "Quantum Cryptography", "Quantum Error Correction", "Bioinformatics Algorithms", "Genomic Data Analysis",
  "Medical Image Processing", "Healthcare Informatics", "E-Commerce Systems", "Content Management Systems", "Social Network Analysis",
  "Recommender Systems", "Collaborative Filtering", "Content Based Filtering", "Reinforcement Learning Agents", "Deep Q Networks",
  "GANs (Generative Adversarial Networks)", "Transformers Architecture", "BERT Model", "GPT Architecture", "Diffusion Models",
  "Explainable AI (XAI)", "AI Ethics", "Bias Mitigation", "Data Privacy Tech", "Federated Learning",

  // ==========================================
  // ELECTRONICS & COMMUNICATION (401 - 500)
  // ==========================================
  "VLSI Design", "ASIC Development", "FPGA Architecture", "Verilog HDL", "VHDL Simulation",
  "Embedded C", "Microcontrollers", "Microprocessors", "Arduino Prototyping", "Raspberry Pi Projects",
  "System on Chip (SoC)", "Digital Signal Processing", "Analog Signal Processing", "Image Processing", "Video Analytics",
  "Wireless Communication", "5G Networks", "6G Technologies", "Satellite Communication", "Radar Systems",
  "Antenna Design", "RF Engineering", "Electromagnetic Fields", "Optical Communication", "Fiber Optics",
  "Printed Circuit Board (PCB)", "Circuit Simulation", "LTSpice Modeling", "Analog Electronics", "Digital Electronics",
  "Power Electronics", "Inverters & Converters", "Semiconductor Devices", "Optoelectronics", "Nanoelectronics",
  "Sensor Networks", "Wireless Sensor Nodes", "MEMS Technology", "Bio Medical Instrumentation", "Signal Telemetry",
  "Telecommunication Systems", "Network Protocols", "LoRaWAN Technology", "ZigBee Networks", "Bluetooth Low Energy",
  "Cellular Networks", "Information Theory", "Coding Techniques", "Error Correction Codes", "Digital Filters",
  "Adaptive Filtering", "VLSI Verification", "CMOS Technology", "Mixed Signal Design", "RF Circuit Design",
  "Microwave Engineering", "Wave Propagation", "Signal Integrity", "Power Integrity", "Electronic Cooling",
  "Hardware Description Languages", "SystemVerilog", "Hardware Security", "Physical Design VLSI", "Logic Synthesis",
  "Static Timing Analysis", "Low Power VLSI", "Neuromorphic Computing", "Printed Electronics", "Flexible Electronics",
  "Avionics Systems", "Flight Instrumentation", "Telemetry Systems", "Instrumentation Amplifiers", "Data Acquisition Systems",
  "PLC Programming", "SCADA Systems", "Industrial Automation", "Industrial IoT (IIoT)", "Modbus Protocol",
  "CAN Bus Architecture", "Automotive Electronics", "Electric Vehicle Hardware", "Battery Management System", "Motor Controllers",
  "Sensors and Actuators", "MEMS Accelerometers", "Biosensors", "Wearable Technology", "Smart Grid Hardware",
  "Power Systems Protection", "Renewable Energy Grid", "Energy Harvesting Circuits", "Optoelectronic Sensors", "Laser Technology",

  // ==========================================
  // ECE SPECIFIC SUB-DOMAINS (501 - 600)
  // ==========================================
  "Hardware In The Loop", "Embedded Linux", "Firmware Engineering", "Bare Metal Programming", "Microcontroller Interfacing",
  "ADC Conversion", "DAC Conversion", "PWM Control", "I2C Protocol", "SPI Protocol",
  "UART Communication", "USB Interface", "Ethernet Controller", "Wi-Fi Modules", "GSM GPRS Modules",
  "GPS Tracking Hardware", "RFID Systems", "NFC Technology", "Biometric Sensors", "Fingerprint Scanners",
  "Pulse Oximeter Sensors", "ECG Signal Processing", "EEG Analysis", "EMG Controlled Systems", "Ultrasonic Transducers",
  "Infrared Sensors", "Gas Sensors", "Smoke Detectors", "Temperature Sensors", "Humidity Sensors",
  "Pressure Transducers", "Load Cells", "Relay Control Board", "Optocouplers", "Voltage Regulators",
  "Switching Power Supplies", "DC DC Converters", "AC DC Inverters", "Frequency Modulators", "Phase Locked Loops",
  "Operational Amplifiers", "Active Filters", "Passive Filters", "RF Transceivers", "Microstrip Antennas",
  "Patch Antennas", "Waveguides", "Fiber Optic Links", "Laser Diodes", "Photodetectors",
  "Solar Cell Characterization", "Supercapacitors", "Piezoelectric Harvesters", "Thermoelectric Generators", "Wireless Power Transfer",
  "Inductive Charging", "Resonant Coupling", "Li-Fi Technology", "Visible Light Communication", "Underwater Communication",
  "Acoustic Communication", "Spread Spectrum Tech", "OFDM Systems", "MIMO Architecture", "Beamforming",
  "Software Defined Radio", "Cognitive Radio Networks", "Dynamic Spectrum Access", "Network Routing Protocols", "Mesh Topology",
  "VLSI Floorplanning", "Placement & Routing", "Clock Tree Synthesis", "Design For Testability", "Built In Self Test",
  "Boundary Scan", "Fault Modeling", "Hardware Trojans", "Cryptographic Hardware", "FPGA Prototyping Board",
  "Xilinx Vivado", "Intel Quartus Prime", "ModelSim Simulation", "Cadence Virtuoso", "Synopsys Design Compiler",

  // ==========================================
  // MECHANICAL ENGINEERING (601 - 700)
  // ==========================================
  "Computer Aided Design (CAD)", "SolidWorks Modeling", "Autodesk Inventor", "CATIA Design", "Finite Element Analysis",
  "ANSYS Simulation", "Computational Fluid Dynamics", "Thermal Analysis", "Structural Analysis", "Kinematics of Machinery",
  "Dynamics of Machines", "Thermodynamics Application", "Heat and Mass Transfer", "Fluid Mechanics", "Hydraulic Systems",
  "Pneumatic Systems", "Internal Combustion Engines", "Automobile Engineering", "Aerodynamics Design", "Wind Tunnel Testing",
  "Turbomachinery", "Power Plant Engineering", "Refrigeration & AC", "HVAC Systems", "Manufacturing Processes",
  "Computer Integrated Manufacturing", "CNC Machining", "Additive Manufacturing", "3D Printing Systems", "Rapid Prototyping Hardware",
  "Material Science", "Composite Materials", "Nanomaterials Fabrication", "Metallurgy", "Mechanical Vibrations",
  "Acoustics Engineering", "Tribology & Lubrication", "Machine Design", "Product Design Engineering", "Reverse Engineering",
  "Geometric Dimensioning", "Design for Manufacturing", "Mechatronics Systems", "Electro Mechanical Design", "Robotic Actuators",
  "MEMS Fabrication", "Smart Materials", "Shape Memory Alloys", "Biomimetic Design", "Biomechanics Hardware",
  "Renewable Energy Systems", "Solar Thermal Collectors", "Wind Turbine Dynamics", "Hydroelectric Turbines", "Geothermal Systems",
  "Automotive Dynamics", "Vehicle Suspension Design", "Chassis Engineering", "Electric Vehicle Drivetrain", "Hybrid Vehicles",
  "Unmanned Aerial Vehicles", "Drone Frame Design", "Propulsion Systems", "Rocket Engineering", "Marine Engineering Systems",
  "Industrial Safety", "Ergonomics Design", "Quality Control Systems", "Six Sigma Certification", "Total Quality Management",
  "Lean Manufacturing", "Supply Chain Engineering", "Operations Research", "Maintenance Engineering", "Non Destructive Testing",
  "Welding Technology", "Metal Casting Analysis", "Sheet Metal Forming", "Plastic Injection Molding", "Tool and Die Design",
  "Robotic Grippers", "Pneumatic Actuators", "Hydraulic Pumps", "Thermofluid Systems", "Cryogenic Engineering",
  "Microfluidics Devices", "MEMS Sensors", "Stress Analysis", "Fatigue Analysis", "Fracture Mechanics",

  // ==========================================
  // MECHANICAL SUB-DOMAINS & TOOLS (701 - 800)
  // ==========================================
  "Stress Strain Analysis", "Modal Analysis", "Transient Thermal Analysis", "Steady State Thermal", "Fluid Structure Interaction",
  "Aerodynamic Lift", "Aerodynamic Drag", "Boundary Layer Flow", "Turbulent Flow Modeling", "Laminar Flow Analysis",
  "Heat Exchangers Design", "Cooling Towers", "Boiler Operation Systems", "Steam Turbines", "Gas Turbines",
  "Four Stroke Engines", "Two Stroke Engines", "Engine Emisson Control", "Catalytic Converters", "Alternative Fuels",
  "Biofuels Production", "Hydrogen Fuel Cells", "Air Conditioning Cycle", "Refrigerants Analysis", "Compressors Engineering",
  "Gears and Gearboxes", "Belts and Pulleys", "Chain Drives", "Clutches and Brakes", "Bearings and Lubricants",
  "Shafts and Couplings", "Fasteners and Joints", "Springs Mechanics", "Cam and Follower", "Linkage Mechanisms",
  "CNC Milling", "CNC Turning", "Laser Cutting Systems", "Plasma Cutting", "Waterjet Cutting",
  "Fused Deposition Modeling", "Stereolithography", "Selective Laser Sintering", "Metal 3D Printing", "Filament Characterization",
  "Powder Metallurgy", "Heat Treatment Steel", "Corrosion Prevention", "Surface Engineering", "Coatings Technology",
  "Polymer Matrix Composites", "Metal Matrix Composites", "Ceramic Matrix Composites", "Carbon Nanotubes", "Graphene Applications",
  "Vibration Isolation", "Damping Materials", "Noise Control Systems", "Shock Absorbers", "Balancing of Rotors",
  "Suspension Systems", "Steering Mechanisms", "Braking Systems Architecture", "Tire Mechanics", "Aerodynamic Wings",
  "Quadcopter Frames", "Fixed Wing Drones", "Rocket Propulsion", "Thrusters Engineering", "Underwater Vehicles ROV",
  "Material Handling Automation", "Conveyor Systems", "Automated Storage Retrieval", "Robotic Palletizing", "Ergonomic Workstations",
  "Statistical Process Control", "Failure Mode Effects", "Root Cause Analysis", "Predictive Maintenance Mechanical", "Condition Monitoring",
  "Ultrasonic Testing", "Radiographic Testing", "Magnetic Particle Testing", "Dye Penetrant Inspection", "Visual Inspection Tools",

  // ==========================================
  // CIVIL & URBAN ENGINEERING (801 - 900)
  // ==========================================
  "Structural Engineering", "Concrete Technology", "Reinforced Concrete Structures", "Steel Design Structures", "Prestressed Concrete",
  "Geotechnical Engineering", "Soil Mechanics", "Foundation Engineering", "Slope Stability Analysis", "Retaining Structures",
  "Transportation Engineering", "Highway Engineering", "Traffic Flow Theory", "Pavement Design", "Railway Engineering",
  "Urban Planning", "Smart Cities Infrastructure", "Geographic Information Systems", "Remote Sensing Data", "GPS Surveying",
  "Environmental Engineering", "Water Treatment Systems", "Wastewater Engineering", "Solid Waste Management", "Air Pollution Control",
  "Hydrology Modeling", "Water Resources Systems", "Open Channel Hydraulics", "Dam Engineering", "Irrigation Systems",
  "Construction Management", "Building Information Modeling", "Autodesk Revit Architecture", "Primavera P3 Planning", "Project Scheduling",
  "Quantity Surveying", "Estimation and Costing", "Building Materials Tech", "Green Building Design", "Sustainable Infrastructure",
  "Earthquake Engineering", "Seismic Isolation", "Structural Dynamics", "Wind Engineering Structures", "Bridge Engineering",
  "Tunneling Technology", "Surveying Techniques", "Total Station Operations", "Photogrammetry", "Geomatics Engineering",
  "Hydraulic Structures", "Coastal Engineering", "Harbor Engineering", "Groundwater Hydrology", "Fluid Pipe Networks",
  "Environmental Impact Assessment", "Hazardous Waste Management", "Rainwater Harvesting", "Eco Friendly Concrete", "Geosynthetics Applications",
  "Soil Stabilization", "Deep Foundations", "Pavement Management Systems", "Traffic Signal Optimization", "Mass Transit Systems",
  "Smart Urban Drainage", "Disaster Management Tech", "Structural Health Monitoring", "Retrofitting of Structures", "Prefabricated Structures",
  "Building Acoustics", "Lighting Design Architecture", "Fire Safety Engineering", "Construction Automation", "3D Concrete Printing",
  "Smart Materials Civil", "Self Healing Concrete", "Carbon Fiber Composites", "Porous Pavements", "Asset Management Systems",
  "Soil Structure Interaction", "Rock Mechanics", "Slope Protection", "Hydrogeology", "Water Distribution Modeling",

  // ==========================================
  // AI & ROBOTICS (901 - 1000)
  // ==========================================
  "Robot Operating System (ROS)", "ROS2 Integration", "Robot Kinematics", "Robot Dynamics", "Inverse Kinematics",
  "Autonomous Mobile Robots", "Unmanned Ground Vehicles", "Humanoid Robotics", "Industrial Robots", "Collaborative Robots (Cobots)",
  "Swarm Robotics", "Drones & Quadcopters", "Autonomous Flight Control", "Simultaneous Localization", "SLAM Algorithms",
  "LiDAR Data Processing", "Sensor Fusion Algorithms", "Kalman Filtering", "Extended Kalman Filters", "Path Planning Algorithms",
  "A Star Algorithm", "Dijkstra Navigation", "Obstacle Avoidance Systems", "Robotic Vision Systems", "Object Detection Robotics",
  "3D Point Cloud Processing", "Deep Reinforcement Learning", "Robotic Gripper Design", "Soft Robotics Systems", "Biomimetic Robots",
  "Medical Robotics", "Surgical Robots", "Exoskeleton Hardware", "Prosthetics Engineering", "Teleoperation Systems",
  "Haptic Feedback Systems", "Micro Robotics", "Nano Robots", "Underwater Robotics (AUV)", "Space Robotics",
  "Robotic Simulation Tools", "Gazebo Simulator", "Webots Environment", "CoppeliaSim Platform", "MATLAB Robotics Toolbox",
  "Actuator Control Systems", "Servo Motor Control", "Stepper Motor Drivers", "Brushless DC Motors", "Robotic Joint Design",
  "IMU Sensor Integration", "Ultrasonic Range Finders", "Time of Flight Sensors", "Computer Vision Robotics", "Visual Odometry",
  "Machine Vision Inspection", "Edge AI Hardware", "NVIDIA Jetson Programming", "Google Coral Edge TPU", "TensorFlow Lite",
  "PyTorch Mobile", "OpenCV Library", "MediaPipe Framework", "Automated Guided Vehicles", "Warehouse Automation Systems",
  "Agriculture Robotics", "Smart Farming Hardware", "Robotic Harvesting", "Drone Mapping Software", "Precision Agriculture",
  "Human Robot Interaction", "Gesture Control Systems", "Voice Controlled Robots", "Brain Computer Interface", "Cognitive Robotics",
  "Evolutionary Robotics", "Genetic Algorithms Robotics", "Fuzzy Logic Controllers", "Neural Control Systems", "Adaptive Control Systems",
  "Robotic Fleet Management", "Cyber Physical Systems", "Digital Twin Technology", "Mechatronics Prototyping", "LabVIEW Automation",
  "Python Robotics Library", "C Plus Plus Robotics", "Embedded Linux Development", "Motion Control Software", "Trajectory Generation"
];
